latency-wait: "5"
jobscript: "lsf_jobscript.sh"
use-conda: "False"
use-singularity: "False"
printshellcmds: "True"
restart-times: "0"
jobs: "500"
cluster: "lsf_submit.py"
cluster-status: "lsf_status.py"
max-jobs-per-second: "50"
max-status-checks-per-second: "10"