static:
  out_dir: 

cellcoal:
  exe: ../../cellcoal/bin/cellcoal-1.1.1
  parameter: cellcoal_parameters.template
  no_rep: 10
  model:
    no_cells: 30
    no_sites: 10000
    pop_size: 10000
    no_muts: 1000
    germline_rate: 0.0005
    brach_rate_var: 1
  scWGA:
    errors: True
    ADO_rate: 0.2
    doublet_rate: [0.02, 0.01]
    ampl_error: [0.01, 0.001, 0]
  NGS:
    seq_cov: 20
    errors: True
    seq_overdis: 5
    seq_error: 0.01

mrbayes:
  exe: /home/hw/Desktop/molClock_project/MrBayes/src/mb
  ngen: 10000000
  ss: False

monovar:
  run: False
  exe: ../../MonoVar_NB/src/monovar.py

scheduler: lsf