static:
  out_dir: 

cellcoal:
  exe: ../../cellcoal/bin/cellcoal-1.2.0
  parameter: templates/cellcoal_parameters.template
  no_rep: 100
  model:
    no_cells: 30
    no_sites: 10000
    pop_size: 10000
    no_muts: 
    mut_rate: 0.000001
    germline_rate: 0.0
    branch_rate_var:   # empty for clock, e.g. 1 for non-clock
    outgroup_branch_length: 1
    binary_alphabet: False
  scWGA:
    errors: False
    ADO_rate: 0.2
    doublet_rate: [0.02, 0.01]
    ampl_error: [0.01, 1e-8, 0]
  NGS:
    seq_cov: 20
    errors: False
    seq_overdis: 5
    seq_error: 0.01
  output:
    tree: True
    full_GT: False
    true_haplotypes: False

monovar:
  run: False
  exe: ../../MonoVar_NB/src/monovar.py

SNP_filter:
  depth: 0
  quality: 0
  singletons: False

tree:
  cellcoal:
    run: True
  scite:
    run: False
    exe: ../../infSCITE/infSCITE
    steps: 10000
  cellphy:
    run: False
    exe: ../../cellphy/cellphy.sh
    command: FAST

mrbayes:
  run: False
  exe: ../../../../MrBayes/src/mb
  use_tree: True
  ngen: [50000]
  ss: True

paup:
  run: False
  learn_tree: False
  exe: ../../paup4a168_ubuntu64 

sieve:
  run: False
  sciphi_exe: ../../SCIPhI/build/sciphi
  beast_bin: ../../beast/bin
  xml: templates/sieve_template.xml
  steps: 10000
  particleCount: 5

poisson:
  run: True
  exclude:

scheduler: 