static:
  out_dir: 

cellcoal:
  exe: ../../cellcoal/bin/cellcoal-1.2.0
  parameter: templates/cellcoal_parameters.template
  no_rep: 100
  model:
    no_cells: 30
    no_sites: 10000
    pop_size: 10000
    no_muts: 1000
    germline_rate: 0.0005
    branch_rate_var: 1
    outgroup_branch_length: 1
    binary_alphabet: False
  scWGA:
    errors: True
    ADO_rate: 0.2
    doublet_rate: [0.02, 0.01]
    ampl_error: [0.01, 1e-8, 0]
  NGS:
    seq_cov: 20
    errors: True
    seq_overdis: 5
    seq_error: 0.01
  output:
    tree: False
    full_GT: False
    true_haplotypes: False

monovar:
  run: False
  exe: ../../MonoVar_NB/src/monovar.py

SNP_filter:
  depth: 5
  quality: 0
  singletons: True

tree:
  cellcoal:
    run: True
  scite:
    run: False
    exe: ../../infSCITE/infSCITE
    steps: 200000
  cellphy:
    run: False
    exe: ../../cellphy/cellphy.sh
    command: SEARCH

mrbayes:
  run: False
  exe: ../../MrBayes/src/mb
  use_tree: True
  ngen: [250000]
  ss: True

paup:
  run: True
  learn_tree: False
  exe: ../../paup4a168_ubuntu64 

sieve:
  run: False
  sciphi_exe: ../../SCIPhI/build/sciphi
  beast_bin: ../../beast/bin
  xml: templates/sieve_template.xml
  steps: 100000

scheduler: slurm