static:
  out_dir: 

cellcoal:
  exe: ../../cellcoal/bin/cellcoal-1.2.0
  parameter: templates/cellcoal_parameters.template
  no_rep: 5
  model:
    no_cells: 100
    no_sites: 10000
    pop_size: 10000
    no_muts:
    germline_rate: 0.0005
    branch_rate_switch: 2
    mut_rate: 8.2e-7 # 1x: 1e-6; 1.5x: 9e-7; 2x: 8.2e-7; 5x: 5.3e-7; 10x: 3.4e-7; 20x: 1.9e-7, 30x: 1.4e-7; 40x: 1.0e-7
    outgroup_branch_length: 1
    root_branch_length: 0.5
    binary_alphabet: False
  scWGA:
    errors: False
    ADO_rate: [0.2, 0.01]
    doublet_rate: [0.02, 0.01]
    ampl_error: [0.01, 1e-8, 0]
  NGS:
    seq_cov: 1
    errors: True
    seq_overdis: 0
    seq_error: 0.01
  output:
    tree: True
    full_GT: False
    true_haplotypes: False

sc_from_bulk:
  run: True
  subsampling: [10, 20]
  no_rep: 2
  errors: False
  NGS:
    seq_cov: 20
    seq_overdis: 5

SNP_filter:
  depth: 5
  quality: 1

tree:
  cellcoal:
    run: True
  scite:
    run: False
    exe: ../../infSCITE/infSCITE
    steps: 10000
  cellphy:
    run: True
    exe: ../../cellphy/cellphy.sh
    command: FAST


poisson:
  dispersion: True
  tree: True
  w_max: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]

paup:
  run: False
  learn_tree: False
  exe: ../../paup4a168_ubuntu64

scheduler: