static:
  out_dir: 

cellcoal:
  exe: ../../cellcoal/bin/cellcoal-1.2.0
  parameter: templates/cellcoal_parameters.template
  no_rep: 100
  model:
    no_cells: 30
    no_sites: 10000
    pop_size: 10000
    no_muts: 1000
    germline_rate: 0.0005
    branch_rate_var:   # empty for clock, e.g. 1 for non-clock
    outgroup_branch_length: 1
    binary_alphabet: False
  scWGA:
    errors: True
    ADO_rate: [0.2, 0.01]
    doublet_rate: [0.02, 0.01]
    ampl_error: [0.01, 1e-8, 0]
  NGS:
    seq_cov: 20
    errors: True
    seq_overdis: 5
    seq_error: 0.01
  output:
    tree: True
    full_GT: False
    true_haplotypes: False

sc_from_bulk:
  run: False
  subsampling: [10, 20]
  no_rep: 2
  errors: False
  NGS:
    seq_cov: 20
    seq_overdis: 0

SNP_filter:
  depth: 5
  quality: 1

tree:
  cellcoal:
    run: True
  scite:
    run: False
    exe: ../../infSCITE/infSCITE
    steps: 200000
  cellphy:
    run: True
    exe: ../../cellphy/cellphy.sh
    command: FAST

poisson:
  dispersion: True
  tree: True
  w_max: [1, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]


paup:
  run: True
  exe: ../../paup4a168_ubuntu64 

scheduler:
