static:
  resources_path: /mnt/lustre/scratch/home/uvi/be/mva/singlecell/Projects/mol_clock/RESOURCES
  WGA_ref: hg19.fasta
  dbsnp: dbsnp_138.hg19.vcf.gz
  indel_db1: Mills_and_1000G_gold_standard.indels.hg19.sites.vcf
  indel_db2: 
  germline: af-only-gnomad.raw.sites.b37.vcf.gz
  gnomAD: small_exac_common_3_b37.vcf.gz

specific:
  data_path: /mnt/lustre/scratch/home/uvi/be/mva/singlecell/Projects/mol_clock/data/S21_P1
  cellnames: acc-cell.txt
  bulk_normal: # SRR6432718
  bulk_samples: [] # [SRR3086498, SRR3086497]
  normal_regex:
  tumor_regex:
  WGA_library: MALBAC
  pair_end: True
  SEQ: WGS
  WES_target: Agilent_SureSelect_Human_All_Exome_V4_hg19/S03723314_Covered.modified.bed
  WES_target_genome: Agilent_SureSelect_Human_All_Exome_V4_hg19/S03723314_Covered.modified.bed.genome 
  PON: PON.SureSelectV5.withchr.vcf.gz

SCcaller:
  run: True
  exe: ../SCcaller_NB/sccaller_v2.0.0_NB.py

monovar:
  run: True
  exe: ../MonoVar_NB/src/monovar.py

mutect:
  filter: contamination

filters:
  depth: 10
  geno_qual: 20

paup:
  exe: ../paup4a168_ubuntu64