static:
  resources_path: /mnt/lustre/scratch/home/uvi/be/mva/singlecell/Projects/mol_clock/RESOURCES
  WGA_ref: hg19.fasta
  dbsnp: dbsnp_138.hg19.vcf.gz
  indel_db1: Mills_and_1000G_gold_standard.indels.hg19.sites.vcf
  indel_db2: 1000G_phase1.indels.b37.vcf
  germline: af-only-gnomad.raw.sites.b37.vcf.gz
  gnomAD: small_exac_common_3_b37.vcf.gz

specific:
  data_path: /mnt/lustre/scratch/home/uvi/be/mva/singlecell/Projects/mol_clock/data/S21_P2
  cellnames: acc-cell.txt
  bulk_normal: # SRR6432718
  bulk_samples: [] # [SRR3086498, SRR3086497]
  WGA_library: MALBAC
  pair_end: True
  SEQ: WGS
  WES_target: Illumina_TruSeq_exome_targeted_regions.hg19.bed
  WES_target_genome: Illumina_TruSeq_exome_targeted_regions.hg19.modified.bed 
  PON: PON.SureSelectV5.withchr.vcf.gz

SCcaller:
  run: True
  exe: /home/uvi/be/nbo/SCcaller_NB/sccaller_v2.0.0_NB.py

monovar:
  run: True
  exe: /home/uvi/be/nbo/MonoVar_NB/src/monovar.py

mutect:
  filter: contamination

filters:
  depth: 10
  geno_qual: 20

modules:
  cutadapt: [pigz, cutadapt/1.18-python-3.7.0]
  bwa: [gcc/6.4.0, bwa/0.7.17]
  picard: [picard/2.18.14]
  gatk41: [gatk/4.1.1.0]
  gatk4: [gatk/4.0.10.0]
  gatk3: [gatk/3.7-0-gcfedb67]
  bedtools: [bedtools/2.28.0]
  SCcaller: [samtools, pysam/0.15.4-python-2.7.17, numpy/1.16.6-python-2.7.17]
  monovar: [samtools,  pysam/0.15.4-python-2.7.17, numpy/1.16.6-python-2.7.17, scipy/1.1.0-python-2.7.15]
  mutect1: [gatk/4.1.1.0, picard/2.18.14]
  QC_seq: [pandas/1.0.1-python-3.7.7, matplotlib/3.1.3-python-3.7.7]
  bcftools: [bcftools]
  QC_calling: [pysam/0.16.0.1-python-3.7.7, pandas/1.0.1-python-3.7.7]
  SciPhi: [gcccore/6.4.0, boost/1.73.0-python-3.7.7, seqan/2.4.0, dlib/19.16, zlib/1.2.11, samtools]