static:
  resources_path: /mnt/lustre/scratch/home/uvi/be/mva/singlecell/Projects/mol_clock/RESOURCES
  WGA_ref: hs37d5.fa
  dbsnp: dbsnp_138.b37.vcf
  indel_db1: Mills_and_1000G_gold_standard.indels.b37.vcf
  indel_db2: 1000G_phase1.indels.b37.vcf
  germline: af-only-gnomad.raw.sites.b37.vcf.gz
  gnomAD: small_exac_common_3_b37.vcf.gz

specific:
  data_path: /mnt/lustre/scratch/home/uvi/be/mva/singlecell/Projects/mol_clock/data/W32
  cellnames: acc-cell.txt
  pair_end: False
  bulk_normal: TNBC_Pop_Normal # SRR1163508
  bulk_samples: [TNBC_Pop_Tumor] # SRR1298936
  normal_regex: TNBC_n\d+
  tumor_regex: [a|h]\d+
  WGA_library: MDA
  SEQ: WES
  WES_target: Illumina_TruSeq_exome_targeted_regions.hg19.modified.bed
  WES_target_genome: Illumina_TruSeq_exome_targeted_regions.hg19.modified.bed.genome
  PON: PON.SureSelectV5.vcf.gz

SCcaller:
  run: True
  exe: ../SCcaller_NB/sccaller_v2.0.0_NB.py

monovar:
  run: True
  exe: ../MonoVar_NB/src/monovar.py

filters:
  depth: 10
  geno_qual: 20

paup:
  exe: ../paup4a168_ubuntu64