static:
  resources_path: /mnt/lustre/scratch/home/uvi/be/mva/singlecell/Projects/mol_clock/RESOURCES
  WGA_ref: hs37d5.fa
  dbsnp: dbsnp_138.b37.vcf
  indel_db1: Mills_and_1000G_gold_standard.indels.b37.vcf
  indel_db2: 1000G_phase1.indels.b37.vcf

specific:
  data_path: /mnt/lustre/scratch/home/uvi/be/mva/singlecell/Projects/mol_clock/data/W32
  cellnames: acc-cell.txt
  bulk_normal: TNBC_Pop_Normal
  bulk_samples: [TNBC_Pop_Normal, TNBC_Pop_Tumor]
  WGA_library: MDA
  SEQ: WES
  WES_target_path: Illumina_TruSeq_exome_targeted_regions.hg19.modified.bed
  
SCcaller:
  run: True
  exe: /mnt/netapp1/posadalab/APPS/sccaller-2.0.0/SCcaller-2.0.0/sccaller_v2.0.0_lab.py

monovar:
  run: True

modules:
  cutadapt: [cutadapt/1.18-python-3.7.0]
  bwa: [gcc/6.4.0, bwa/0.7.17]
  picard: [picard/2.18.14]
  gatk: [gatk/4.0.10.0]
  bedtools: [bedtools/2.28.0]
  SCcaller: [samtools, pysam, numpy/1.16.6-python-2.7.17]
  monovar: [gcc/6.4.0, samtools, monovar/140316-python-2.7.15, scipy/1.1.0-python-2.7.15]
  QC_seq: [pandas/1.0.1-python-3.7.7, matplotlib/3.1.3-python-3.7.7]