static:
  resources_path: /mnt/lustre/scratch/home/uvi/be/mva/singlecell/Projects/mol_clock/RESOURCES
  WGA_ref: hs37d5.fa
  dbsnp: dbsnp_138.b37.vcf
  indel_db1: Mills_and_1000G_gold_standard.indels.b37.vcf
  indel_db2: 1000G_phase1.indels.b37.vcf
  germline: af-only-gnomad.raw.sites.b37.vcf.gz
  gnomAD: small_exac_common_3_b37.vcf.gz
  QC_seq: False

specific:
  data_path: /mnt/lustre/scratch/home/uvi/be/mva/singlecell/Projects/mol_clock/data/Wang_redo/W55
  cellnames: acc-cell.txt
  pair_end: False
  bulk_normal: BCN # SRR1153401
  bulk_samples: [BCT] # [SRR1153400]
  WGA_library: MDA
  SEQ: WES
  WES_target: Illumina_TruSeq_exome_targeted_regions.hg19.modified.bed
  WES_target_genome: Illumina_TruSeq_exome_targeted_regions.hg19.modified.bed.genome
  PON: PON.SureSelectV5.vcf.gz

SCcaller:
  run: True
  exe: /mnt/netapp1/posadalab/APPS/sccaller-2.0.0/SCcaller-2.0.0/sccaller_v2.0.0_lab.py

monovar:
  run: True
  exe: /home/uvi/be/nbo/MonoVar_NB/src/monovar.py

filters:
  depth: 10
  QUAL: 20

modules:
  cutadapt: [pigz, cutadapt/1.18-python-3.7.0]
  bwa: [gcc/6.4.0, bwa/0.7.17]
  picard: [picard/2.18.14]
  gatk41: [gatk/4.1.1.0]
  gatk4: [gatk/4.0.10.0]
  gatk3: [gatk/3.7-0-gcfedb67]
  bedtools: [bedtools/2.28.0]
  SCcaller: [samtools, pysam/0.15.4-python-2.7.17, numpy/1.16.6-python-2.7.17]
  monovar: [samtools,  pysam/0.15.4-python-2.7.17, numpy/1.16.6-python-2.7.17, scipy/1.1.0-python-2.7.15]
  QC_seq: [pandas/1.0.1-python-3.7.7, matplotlib/3.1.3-python-3.7.7]
  bcftools: [bcftools]
  QC_calling: [pysam/0.16.0.1-python-3.8.1, pandas/1.0.0-python-3.8.1]