static_data:
  data_path: /mnt/lustre/scratch/home/uvi/be/mva/singlecell/Projects/mol_clock/data/Wu61
  resources_path: /mnt/netapp1/posadalab/phylocancer/RESOURCES/
  WGA_ref: hs37d5.fa
  SEQ: WES


cutadapt:
  WGA_library: AMPLI-1


WES:
  resources_path: /mnt/lustre/scratch/home/uvi/be/mva/singlecell/Projects/mol_clock/data/resources
  target_path: Agilent_SureSelect_Clinical_Research_Exome/S06588914_Covered.modified.bed
  
  
base_recal:
  dbsnp: dbsnp_138.b37.vcf
  indel_db: Mills_and_1000G_gold_standard.indels.b37.vcf
  indel_db2: 1000G_phase1.indels.b37.vcf


SCCaller:
  run: True
  exe: /mnt/netapp1/posadalab/APPS/sccaller-2.0.0/SCcaller-2.0.0/sccaller_v2.0.0_lab.py
