static:
  resources_path: /mnt/lustre/scratch/home/uvi/be/mva/singlecell/Projects/mol_clock/RESOURCES
  WGA_ref: hs37d5.fa
  dbsnp: dbsnp_138.b37.vcf
  indel_db1: Mills_and_1000G_gold_standard.indels.b37.vcf
  indel_db2: 1000G_phase1.indels.b37.vcf
  germline: af-only-gnomad.raw.sites.b37.vcf.gz
  gnomAD: small_exac_common_3_b37.vcf.gz

specific:
  data_path: /mnt/lustre/scratch/home/uvi/be/mva/singlecell/Projects/mol_clock/data/Wu61
  cellnames: acc-cell.txt
  pair_end: True
  bulk_normal: CRC0907-Normal # SRR308649
  bulk_samples: [CRC0907-Cancer, CRC0907-Polyps] # [SRR3086498, SRR3086497]
  normal_regex: CRC0907-N\d
  tumor_regex:
  WGA_library: REPLI-G
  SEQ: WES
  WES_target: Agilent_SureSelect_Human_All_Exome_V4_hg19/S03723314_Covered.modified.bed
  WES_target_genome: Agilent_SureSelect_Human_All_Exome_V4_hg19/S03723314_Covered.modified.bed.genome 
  PON: PON.SureSelectV5.withchr.vcf.gz

SCcaller:
  run: True
  exe: ../SCcaller_NB/sccaller_v2.0.0_NB.py

monovar:
  run: True
  exe: ../MonoVar_NB/src/monovar.py

mutect:
  filter: contamination

filters:
  depth: 10
  geno_qual: 20

paup:
  exe: ../paup4a168_ubuntu64