cellcoal:
  exe: ../../cellcoal/bin/cellcoal-1.1.1
  parameters: parameters.simulations_clock.DP


mrbayes:
  exe: /home/hw/Desktop/molClock_project/MrBayes/src/mb
  ngen: 10000000
  ss: False


hpc: True
